/* Mutator: Configuration */

CREATE OR REPLACE TABLE MTCFG (
    Compile_Program
        CHAR(10) CCSID 37                   
    ,                                       
    Compile_Library
        CHAR(10) CCSID 37                   
    ,    
    mtfIdentity                                                
        BIGINT GENERATED BY DEFAULT AS IDENTITY             
        CONSTRAINT PK_MTCFG PRIMARY KEY                   
);

LABEL ON TABLE MTCFG
    IS 'Mutator: Configuration';                                     
                                                            