/* Mutator: Files */

CREATE OR REPLACE TABLE MTFIL (                     
    Long_Schema                             
        VARCHAR(128) CCSID 37               
    ,                                       
    Short_Schema                            
        CHAR(10) CCSID 37                   
    ,                                       
    Long_Table                              
        VARCHAR(128) CCSID 37               
    ,                                       
    Short_Table                             
        CHAR(10) CCSID 37                   
    ,                                       
    File_Type                               
        VARCHAR(10) CCSID 37                
    ,                                       
    SQL_Type                                
        VARCHAR(9) CCSID 37                 
    ,                                       
    Source_File                             
        VARCHAR(10) CCSID 37                                
    ,                                                       
    Source_Library                                          
        VARCHAR(10) CCSID 37                                
    ,                                                       
    Source_Member                                           
        VARCHAR(10) CCSID 37                                
    ,                                                       
    mtfIdentity                                                
        BIGINT GENERATED BY DEFAULT AS IDENTITY             
        CONSTRAINT PK_MTFIL PRIMARY KEY                   
    );                                                      
                                                            
LABEL ON TABLE MTFIL                                      
    IS 'Mutator: Files';                                     
                                                            