/* Mutator: File/File Cross Reference */

CREATE OR REPLACE TABLE MTFILFIL (                                          
    Parent_File                                                  
        BIGINT NOT NULL                                          
        CONSTRAINT MTFILFIL_C1 REFERENCES MTFIL(mtfIdentity)      
        ON DELETE RESTRICT ON UPDATE RESTRICT                    
    ,                                                            
    Child_File                                                   
        BIGINT NOT NULL                                          
        CONSTRAINT MTFILFIL_C2 REFERENCES MTFIL(mtfIdentity)      
        ON DELETE RESTRICT ON UPDATE RESTRICT                    
    ,                                                            
    mtffIdentity                                                     
        BIGINT GENERATED BY DEFAULT AS IDENTITY                  
        CONSTRAINT PK_MTFILFIL PRIMARY KEY                       
    );                                                           
        
LABEL ON TABLE MTFILFIL                 
    IS 'Mutator: File/File Cross Reference';              
                                        