/* Mutator: File Fields */

CREATE OR REPLACE TABLE MTFILFLD (                                             
    File                                                            
        BIGINT NOT NULL                                             
        CONSTRAINT MTFILFLD_C1 REFERENCES MTFIL(mtfIdentity)         
        ON DELETE RESTRICT ON UPDATE RESTRICT                       
    ,                                                               
    Long_Column                                                     
        VARCHAR(128) CCSID 37                                       
    ,                                                               
    Short_Column                                                    
        CHAR(10) CCSID 37                                           
    ,                                                               
    Column_Type                                                     
        VARCHAR(8) CCSID 37                                         
    ,                                                               
    Column_Length                                                   
        INT                                                         
    ,                                                               
    Column_Scale                                                    
        INT                                                         
    ,                                                       
    mtffIdentity                                                
        BIGINT GENERATED BY DEFAULT AS IDENTITY             
        CONSTRAINT PK_MTFILFLD PRIMARY KEY                  
    );                                                      
                                                            
LABEL ON TABLE MTFILFLD
    IS 'Mutator: File Fields';                                  
                                                            