/* Mutator: File Fields */

CREATE OR REPLACE TABLE MTFILFLD (                                             
    File                                                            
        BIGINT NOT NULL                                             
        CONSTRAINT MTFILFLD_C1 REFERENCES MTFIL(mtfIdentity)         
        ON DELETE RESTRICT ON UPDATE RESTRICT                       
    ,                                                               
    Long_Column          
        FOR COLUMN COLUMN                                           
        VARCHAR(128) CCSID 37                                       
    ,                                                               
    Short_Column     
        FOR COLUMN SYSCOLUMN                                               
        CHAR(10) CCSID 37                                           
    ,                                                               
    Column_Type      
        FOR COLUMN TYPE                                               
        VARCHAR(8) CCSID 37                                         
    ,                                                               
    Column_Length   
        FOR COLUMN LENGTH                                                
        INT                                                         
    ,                                                               
    Column_Scale    
        FOR COLUMN SCALE                                                
        INT                                                         
    ,                                                   
    Column_Label
        FOR COLUMN HEADINGS
        VARCHAR(60)
    ,
    Column_Text
        FOR COLUMN TEXT 
        VARCHAR(50)
    ,
    mtffIdentity      
        FOR COLUMN IDENTITY                                          
        BIGINT GENERATED BY DEFAULT AS IDENTITY             
        CONSTRAINT PK_MTFILFLD PRIMARY KEY                  
    );                                                      

RENAME TABLE MTFILFLD TO Mutator_File_Fields
    FOR SYSTEM NAME MTFILFLD;            

LABEL ON TABLE MTFILFLD
    IS 'Mutator: File Fields';                                  
                                                            