/* Mutator: Files */

CREATE OR REPLACE TABLE MTFIL (                     
    Long_Schema          
        FOR COLUMN SCHEMA                   
        VARCHAR(128) CCSID 37               
    ,                                       
    Short_Schema                            
        FOR COLUMN SYSSCHEMA
        CHAR(10) CCSID 37                   
    ,                                       
    Long_Table             
        FOR COLUMN TABLE                 
        VARCHAR(128) CCSID 37               
    ,                                       
    Short_Table                        
        FOR COLUMN SYSTABLE     
        CHAR(10) CCSID 37                   
    ,                                       
    File_Type                      
        FOR COLUMN FILETYPE         
        VARCHAR(10) CCSID 37                
    ,                                       
    SQL_Type               
        FOR COLUMN SQLTYPE                 
        VARCHAR(9) CCSID 37                 
    ,                                       
    Source_File         
        FOR COLUMN SRCFILE                    
        VARCHAR(10) CCSID 37                                
    ,                                                       
    Source_Library    
        FOR COLUMN SRCLIB                                     
        VARCHAR(10) CCSID 37                                
    ,                                                       
    Source_Member    
        FOR COLUMN SRCMBR                                       
        VARCHAR(10) CCSID 37                                
    ,                                                       
    mtfIdentity        
        FOR COLUMN IDENTITY                                        
        BIGINT GENERATED BY DEFAULT AS IDENTITY             
        CONSTRAINT PK_MTFIL PRIMARY KEY                   
    );                                                      

RENAME TABLE MTFIL TO Mutator_Files
    FOR SYSTEM NAME MTFIL;            
                                                            
LABEL ON TABLE MTFIL                                      
    IS 'Mutator: Files';                                     
                                                            