/* Mutator: Program/File Cross Reference */

CREATE OR REPLACE TABLE MTPGMFIL (                                         
    Program                                                  
        BIGINT NOT NULL                                      
        CONSTRAINT MTPGMFIL_C1 REFERENCES MTPGM(mtpIdentity)      
        ON DELETE RESTRICT ON UPDATE RESTRICT                
    ,                                                        
    File                                                     
        BIGINT NOT NULL                                      
        CONSTRAINT MTPGMFIL_C2 REFERENCES MTFIL(mtfIdentity)     
        ON DELETE RESTRICT ON UPDATE RESTRICT                
    ,                                                        
    mtpfIdentity                                                 
        BIGINT GENERATED BY DEFAULT AS IDENTITY              
        CONSTRAINT PK_MTPGMFIL PRIMARY KEY                      
    );                                                       
                                                             
LABEL ON TABLE MTPGMFIL              
    IS 'Mutator: Program/File Cross Reference';                                                                         