/* Mutator: Program Fields */

CREATE OR REPLACE TABLE MTPGMFLD (                                              
    Program                                                          
        BIGINT NOT NULL                                              
        CONSTRAINT MTPGMFLD_C1 REFERENCES MTPGM(mtpIdentity)            
        ON DELETE RESTRICT ON UPDATE RESTRICT                        
    ,                                                                
    Procedure                                                        
        VARCHAR(128) CCSID 37                                        
    ,                                                                
    Field                                                            
        CHAR(50) CCSID 37                                            
    ,                                                                
    Attribute                                                        
        CHAR(10) CCSID 37                                            
    ,                                                                
    Reference                                                        
        CHAR(12) CCSID 37                                            
    ,                                                                
    mtpfIdentity                                                         
        FOR COLUMN IDENTITY
        BIGINT GENERATED BY DEFAULT AS IDENTITY                      
        CONSTRAINT PK_MTPGMFLD PRIMARY KEY               
    );                                                   
                                                         
RENAME TABLE MTPGMFLD TO Mutator_Program_Fields
    FOR SYSTEM NAME MTPGMFLD;            

LABEL ON TABLE MTPGMFLD                                  
    IS 'Mutator: Program Fields';                            
                                                         