/* Mutator: Programs */

CREATE OR REPLACE TABLE MTPGM (                    
    Long_Schema                    
        FOR COLUMN SCHEMA        
        VARCHAR(128) CCSID 37              
    ,                                      
    Short_Schema      
        FOR COLUMN SYSSCHEMA                     
        CHAR(10) CCSID 37                  
    ,                                      
    Long_Program            
        FOR COLUMN PROGRAM               
        VARCHAR(128) CCSID 37              
    ,                                      
    Short_Program   
        FOR COLUMN SYSPROGRAM                       
        CHAR(10) CCSID 37                  
    ,                                      
    Program_Type   
        FOR COLUMN PGMTYPE                        
        VARCHAR(10) CCSID 37               
    ,                                      
    Program_Attribute     
        FOR cOLUMN PGMATTR                 
        VARCHAR(10) CCSID 37               
    ,                                      
    Source_File      
        FOR COLUMN SRCFILE                           
        VARCHAR(10) CCSID 37                     
    ,                                            
    Source_Library   
        FOR COLUMN SRCLIB                            
        VARCHAR(10) CCSID 37                     
    ,                                            
    Source_Member   
        FOR COLUMN SRCMBR                            
        VARCHAR(10) CCSID 37                     
    ,                                            
    mtpIdentity      
        FOR COLUMN IDENTITY                               
        BIGINT GENERATED BY DEFAULT AS IDENTITY  
        CONSTRAINT PK_MTPGM PRIMARY KEY         
    );                                           
                                     
RENAME TABLE MTPGM TO Mutator_Programs
    FOR SYSTEM NAME MTPGM;            
                                                 
LABEL ON TABLE MTPGM
    IS 'Mutator: Programs';                        
                                                                                            