/* Mutator: Program DataStructures */

CREATE OR REPLACE TABLE MTPGMDS (                                              
    Program                                                          
        BIGINT NOT NULL                                              
        CONSTRAINT MTPGMDS_C1 REFERENCES MTPGM(mtpIdentity)            
        ON DELETE RESTRICT ON UPDATE RESTRICT                        
    ,                                                                
    DataStructure   
        FOR COLUMN STRUCT
        CHAR(50) CCSID 37                                            
    ,                                                                
    File                                                        
        CHAR(50) CCSID 37                                            
    ,                                                                
    mtpdIdentity                                                         
        FOR COLUMN IDENTITY
        BIGINT GENERATED BY DEFAULT AS IDENTITY                      
        CONSTRAINT PK_MTPGMDS PRIMARY KEY               
    );                                                   
                                                         
RENAME TABLE MTPGMDS TO Mutator_Program_DataStructures
    FOR SYSTEM NAME MTPGMDS;            

LABEL ON TABLE MTPGMDS                                  
    IS 'Mutator: Program DataStructures';                            
                                                         
